name: alius_vpn
description: AliusVPN — лучший личный VPN клиент
version: 2.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray_client: ^3.1.0
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
